### ISSUE TITLE
wrong table name in services.yml and parameters.yml

### ISSUE THREAD

**Issue by 3D-I** [phpbb-extensions/phpbb-ext-skeleton#63]
Here's what's created there into those 2 files
> demo_table

but the schema migration file say
> $this->table_prefix . 'acme_demo'

**Comment by VSEphpbb** [comment]
They are not the same table. Neither one is ever actually used in any of the sample code.

One is created by theservice, because the servce shows how a table name can be passed into it for usage (that's demo_table).

The other (acme_demo) is just part of a migration that is doing schema changes, to show in addition to adding columns, how to add a table.

**Comment by 3D-I** [comment]
Ok, let's call this a lack of consistency but's ok.
