### ISSUE TITLE
language file not created just for the listener - hard-coded language var in listener.php

### ISSUE THREAD

**Issue by 3D-I** [phpbb-extensions/phpbb-ext-skeleton#64]
> $forum_row['FORUM_NAME'] .= ' :: Acme Event ::';
I think it should be better to get the language file also if you choose to have just the event listener instead to have an hard-coded string in there.

**Comment by VSEphpbb** [comment]
Ggain this is just sample code. The PHP Event Listener componenet is only meant to output a PHP Event listener. There's no telling what it could be used for. It's up to the ext developer to add all the extra stuff they will need, from language files, db and config objects and all the other stuff.

This component is intentionally written to not use any dependencies or other extra files, and simply show how to update overloaded listener events.

If you look at what this event actually does, you'd see it is totally ridiculous. It's sole purpose is to show how an event can be used, and that it's effect is visible on the forum. So it's kept simple because, obviously, it should immediately be deleted and replaced with productive code ;)

**Comment by 3D-I** [comment]
Again ok, I simply have another vision of this extension. Anyway. ;)
